config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  authenticated :user do
    root to: "categories#index", as: :authenticated_root
  end

  unauthenticated :user do
    root "home#index", as: :unauthenticated_root
  end

  resources :users
  resources :categories, only: %i[index show new create] do
    resources :items, only: %i[new create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :item_categories, dependent: :destroy
  has_many :items, through: :item_categories, dependent: :destroy

  validates :name, :icon, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :item_categories, dependent: :destroy
  has_many :categories, through: :item_categories, dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :category_ids, presence: true
end

app/models/item_category.rb
class ItemCategory < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :categories, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # def after_sign_out_path_for(resource_or_scope)
  #   root_path
  # end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.where(author_id: current_user.id).includes([:items]).order('created_at DESC')
  end

  def show
    if current_user.id.to_i == Category.find(params[:id]).author_id.to_i
      @category = Category.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.author_id = current_user.id
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # skip_before_action :authenticate_user!
  def index
    render
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def new
    @category = Category.find(params[:category_id])
    @item = @category.items.build
    @all_categories = Category.where(author_id: current_user.id)
  end

  def create
    @category = Category.find(params[:category_id])
    @item = Item.new(item_params)
    @item.author_id = current_user.id

    if @item.save
      redirect_to category_path(params[:category_id]), notice: 'Item was successfully added.'
    else
      @all_categories = Category.where(author_id: current_user.id)
      flash.now[:alert] = 'Failed to create item.'
      render :new
    end
  end

  def item_params
    params.require(:item).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.includes(:items, :categories)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon_options
    [
      ['Default', 'fa-solid fa-circle'],
      ['Star', 'fa-solid fa-star'],
      ['Phone', 'fa-solid fa-phone'],
      ['House', 'fa fa-home'],
      ['Backward', 'fa-solid fa-backward'],
      ['Burger', 'fa-solid fa-burger'],
      ['Food', 'fa-solid fa-bowl-food'],
      ['Music', 'fa-solid fa-music'],
      ['List', 'fa-solid fa-list'],
      ['Shopping', 'fa-solid fa-cart-shopping'],
      ['Bills', 'fa-solid fa-money-bill']
    ]
  end
end

app/views/categories/index.html.erb
<div class="flex h-16 bg-blue-500 justify-between text-white sticky top-0 pl-5 m-0">
  <%= link_to '/' do %>
    <div class="space-y-2 ml-3">
      <div class="w-8 h-0.5 bg-white"></div>
      <div class="w-8 h-0.5 bg-white"></div>
      <div class="w-8 h-0.5 bg-white"></div>
    </div>
  <% end %>

  <h1 class="text-center text-4xl"> TRANSACTIONS </h1>
  <div></div>
</div>
<div class="flex flex-col w-full p-5 mx-auto">
  <div class="flex flex-col">
    <% @categories.each do |category| %>
      <ul class="flex bg-white justify-between gap-7 p-5 mt-7">
        <li class="flex">
          <%= link_to category_path(category.id), class: "flex gap-5" do %>
            <% if category.icon.start_with?('fa') %>
              <i class="<%= category.icon %> text-5xl text-teal-600" aria-hidden="true"></i>
            <% else %>
              <img src="<%= category.icon %>" alt="<%= category.name %>">
            <% end %>
            <div class="">
              <p> <%= category.name %></p>
              <p> <%= category.created_at.strftime('%d-%b-%Y') %></p>
            </div>
          <% end %>
        </li>
        <li>
          $<%= category.items.sum(:amount) %>
        </li>
      </ul>
    <% end %>
  </div>

  <div class="flex w-full bg-green-500 border p-2 fixed inset-x-0 bottom-0 h-25">
    <%= link_to "NEW CATEGORY", new_category_path, class: 'text-center border-2 w-full mx-7 p-5 text-white' %>
  </div>

</div>

app/views/categories/new.html.erb
<div class="flex h-16 bg-blue-500 justify-between text-white sticky top-0 pl-5 m-0">
  <div class="">
      <%= link_to categories_path do %>
        <i class="fa-solid fa-backward mt-3"></i>
      <% end %>
    </div>
  <h1 class="text-4xl">ADD NEW TRANSACTIONS</h1>
  <div></div>
</div>
<div class="flex flex-col justify-center p-5 mx-0 w-5/6">
  <%= form_with(model: @category, url: categories_path, local: true, id: "new_category") do |form|  %>
    <div class="flex flex-col gap-2">
      <%= form.hidden_field :icon, id: 'icon-hidden-field' %>
      <div class="flex flex-col">
        <%= form.text_field :name, placeholder: 'Category Name' %>
      </div>
      <div class="flex flex-col">
        <%= form.select :select_icon, options_for_select(icon_options), { include_blank: 'Select icon' }, id: 'dropdown-icon', onchange: 'updateHiddenField(this.value)' %>
      </div>

      <div class="flex flex-col">
        <%= form.text_field :text_icon, placeholder: 'Or Paste Icon Link', id: 'text-icon', oninput: 'updateHiddenField(this.value)' %>
      </div>
    </div>
    <%= form.submit "Add Category", class:"rounded border-2 border-slate-400 bg-white p-2 mt-4 " %>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="flex h-16 bg-blue-500 justify-between text-white sticky top-0 pl-5 m-0">
  <div class="">
    <%= link_to categories_path do %>
      <i class="fa-solid fa-backward mt-3"></i>
    <% end %>
  </div>
  <h1 class="text-center text-4xl"> DETAILS </h1>
  <div></div>
</div>
<div class="flex flex-col w-full p-5 mx-auto">
  <div class="flex flex-col justify-between">
    <div class="flex bg-white justify-start gap-7 p-5 my-7">
      <% if @category.icon.start_with?('fa') %>
        <i class="<%= @category.icon %> text-5xl text-teal-600" aria-hidden="true"></i>
      <% else %>
        <img src="<%= @category.icon %>" alt="<%= @category.name %>">
      <% end %>
      <p class="mt-3"> <%= @category.name %></p>
    </div>
    <% total =0%>
    <% @category.items.each do |item| %>
      <ul class="flex bg-white justify-between gap-7 p-5 border-b-2">
        <li class="flex">
          <div class="">
            <p class="text-bold text-xl"> <%= item.name %></p>
            <p class="text-sm text-gray-500"> <%= item.created_at.strftime('%d-%b-%Y') %></p>
          </div>
        </li>
        <li>
          $<%= item.amount %>
        </li>
      </ul>
      <% total += item.amount%>
    <% end %>
    <div class="flex bg-white justify-between gap-7 p-5">
      <p class="text-bold text-xl">TOTAL PAYMENT</p>
      <p class="text-bold text-xl">$<%= total%></p>
    </div>
  </div>

  <div class="flex w-full bg-green-500 border p-2 fixed inset-x-0 bottom-0 h-25">
    <%= link_to "NEW ITEM", new_category_item_path(@category) , class: 'text-center border-2 w-full mx-7 p-5 text-white' %>
  </div>
</div>

app/views/home/index.html.erb
<div class="flex justify-center my-3">
  <h1 class="text-4xl p-5"> Welcome to the Expense tracker application! </h1>
</div>

<div class="w-2/3 mx-auto">
  <p class="text-justify"> The Expense Tracker Application is a digital tool designed to help individuals or businesses manage their financial transactions and monitor their spending habits. This app enables users to record and categorize their expenses, track income sources, and generate visual reports for better financial insights. Users can input various types of transactions, such as purchases, bills and income into the app. With its user-friendly interface, the Expense Tracker Application aims to assist users in keeping track of their money and maintaining a clear overview of their financial health. </p>

  <div class="text-xl py-5">
    Please <%= link_to "Sign Up", new_user_registration_path, class:'hover:text-violet-600' %> or <%= link_to "Log In", user_session_path, class:'hover:text-blue-500' %> to continue
  </div>
</div>

app/views/items/new.html.erb
<% if @item.errors.any? %>
   <div class="text-red-500 text-center">
    <p><%= pluralize(@item.errors.count, "error") %> found:</p>

    <ul class="text-bold">
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    </div>
<% end %>
<div class="flex h-16 bg-blue-500 justify-between text-white sticky top-0 pl-5 m-0">
  <div class="">
      <%= link_to category_path(params[:category_id]) do %>
        <i class="fa-solid fa-backward mt-3"></i>
      <% end %>
    </div>
    <h1 class="py-5">ADD NEW EXPENSE</h1>
    <div></div>
  </div>
  <div class="flex flex-col justify-center p-5 mx-0 w-5/6">
    <%= form_with(model: @item, url: category_items_path(@category), local: true) do |form|  %>
      <div class="flex flex-col gap-5">
        <%= form.text_field :name, placeholder: 'Expense Name' %>

        <%= form.text_field :amount, placeholder: 'Expense Amount' %>
      </div>
      <div class="form-group">
        <label>Select Categories:</label>
        <% @all_categories.each do |category| %>
          <label>
            <%= check_box_tag "item[category_ids][]", category.id %>
            <%= category.name %>
          </label>
        <% end %>
      </div>
      <%= form.submit "Add expense", class:"rounded border-2 border-slate-400 bg-white p-2 mt-4" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpenseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "category_form" %>

  </head>

  <body class="bg-slate-300 text-slate-900">
    <%= render partial: 'shared/navigation' %>
    <p class="notice flex w-full bg-blue-500 text-amber-400 pl-5"><%= notice %></p>
    <p class="alert flex w-full bg-blue-500 text-red-600 p-5"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navigation.html.erb
<header class="h-12 bg-blue-500 text-white sticky top-0">
  <ul class="flex flex-row justify-end gap-7 p-5 pb-0">
    <% if user_signed_in? %>
      <li><%= link_to "Categories", categories_path %></li>
      <li><%= button_to( "Log Out", destroy_user_session_path, method: :delete ) %></li>
    <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <li><%= link_to "Log In", user_session_path %></li>
    <% end %>
  </ul>
</header>